In [1]:
import numpy as np

###### Carlos Fleck 14009335
# Diferencias entre np.array y np.matrix

Las matrices en numpy son muy utilizadas ya que permiten los trabajos en dimensiones. Existen distintos tipos de creacion dentro de numpy que es con listas anidadas arreglos de numpy o las matrices de numpy.

### np.array

###### Que es un np.array en python?
Este es una coleccion de elementos con una limtante N que se parece mucho a las secuencias de python tales como las listas. Tiene propiedades muy similares con algunas propiedades extras que lo hacen muchisimo mas util. 


In [8]:
arreglo =np.array([1,2,3,4,5,6,7])
print(np.size(arreglo))
print(arreglo)

7

Como podemos ver, su construccion es bastante sencilla y su manipulacion tambien. Todos los elementos tienen que ser homogeneos, o sea el mismo tipo. Si se agregan elementos de diferente tipo, el arreglo sera del tipo que sea mayoria. Esto se trabaja bien a no ser que sea un tipo string.

Por que se utilizan arrays?
Python es un lenguaje dinamico y los loops son muy costosos. Con las matrices se pueden tardar en rangos de milisegundos el visualizar la lista, sin embargo. Numpy cuenta con optimizaciones que hacen que las operaciones sean mucho mas rapidas dejando en el rango de los micro segundos


### np.matrix

###### Que es np.matrix en python?

Esta como los arrays son una coleccion de elementos sin embargo a diferencia de los arreglos, las matrices son una especie multidimencional estrictamente de dos dimensiones. Las matrices por lo genreal utilizan columnas y filas y ambas estan definidas en la clase matrix.

Existen varias formas de operar las matrices. como mencione antes los loops son muy costosos en python sin embargo con numpy se puede hacer sumas o multiplicaciones sencillas.


In [13]:
a=np.matrix([[1,2],[1,2]])
a

matrix([[1, 2],
        [1, 2]])

In [14]:
b=np.matrix([[2,1],[2,1]])
b

matrix([[2, 1],
        [2, 1]])

In [15]:
a+b

matrix([[3, 3],
        [3, 3]])

Como pudimos apreciar es sencillo de implementar.

##Cual es la diferencia entre matrices y arrays?

Las matrices como se menciona anteriormente son bidimensionales estrictamente. no cuentan con la caracteristica de ser tridimensionales o tetradimensionales. 
Los arrays al ser anidados pueden almacenar tantas dimensiones como se desee.

aqui un ejemplo de un array unidimensional y tridimensional


In [22]:
unidim=np.array([1,1,1,1,1,1,1])

array([1, 1, 1, 1, 1, 1, 1])

In [21]:
tridi=np.array([[[1]*4]*4]*4)
tridi

array([[[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]]])

Ahora intentemos hacerlo con matrix

In [23]:
matriz=np.matrix([[[1]*4]*4]*4)

ValueError: matrix must be 2-dimensional

Como se puede apreciar no es posible hacerlo debido a la limitante bidimencional de las matrices definidas por numpy

# Ejercicios Clase 8

**Ejercicio aplicado en DS**
Se tiene una red neuronal sencilla(y simplificada) como la de la siguiente imagen:
<img src="https://www.oreilly.com/library/view/practical-convolutional-neural/9781788392303/assets/246151fb-7893-448d-b9bb-7a87b387a24b.png">

Donde:
* INPUT LAYER: un vector X de tamaño = 2 que representa los datos de entrada
* HIDDEN_LAYER :capa oculta con 2 neuronas definidas por los vectores:
    * HL1 = [0.25,0.37]
    * HL2 = [-8,14]
* OUTPUT_LAYER = capa de salida definida por el vector [4,9]

Crear una funcion neural_network(X) para calcular:
* Calcule la salida de cada neurona en la capa intermedia aplicada a la capa de entrada.
* Use el resultado del paso anterior como entrada para la neurona en la capa de salida

Utilizando multiplicación de matrices se debe calcular para cada fila de la matriz de entrada X el valor de las neuronas de la capa intermedia, esto producirá una nueva matriz con el mismo número de filas que X y 2 columnas(1 para cada neurona) , a  los valores de esta matriz se les debe aplicar la función "sigmoid"(descrita a continuación) para limitarlos al intervalo de 0 a 1, esto produce una matriz del mismo tamaño pero con valores entre 0 a 1, esta matriz se multiplica matricialmente por la matriz que representa los pesos de la capa de salida  y este proceso produce un nuevo tensor al cual se debe aplicar nuevamente la función sigmoid. El resultado debe ser un tensor con el mismo número de filas que la matriz X y una sola columna(una predicción para cada fila de X.

<img src="https://cdn-images-1.medium.com/max/1600/1*Xu7B5y9gp0iL5ooBj7LtWw.png">

### Ejercicio  2

Implementar en una funcion neural_network(X) la red neuronal definida por la siguiente arquitectura:

<img src="http://i.imgur.com/UNlffE1.png">

Podemos validar si fue correctamente implementada si usamos como entrada el vector x=[1,1] . Debemos obtener el resultado mostrado en la imagen.

Una vez tenemos la implementacion correcta, cambiar la funcion de activacion de la capa de salida por la funcion de activacion ReLu(https://en.wikipedia.org/wiki/Rectifier_(neural_networks)):

<img src="https://cdn-images-1.medium.com/max/1600/1*DfMRHwxY1gyyDmrIAd-gjQ.png">

Luego evaluar la red neuronal sobre la matriz de datos X(de manera vectorizada):